html/themes/custom/pocam_common_design/sass/pocam_custom/_home.scss

Merged the last request without waiting for the tests to pass. Testing again.

{POCAM-57] trigger build again

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

Prompted by https://humanitarian.atlassian.net/jira/software/c/projects/POCAM/issues/POCAM-58 - this brings in recent changes to packages in the subtheme.

[POCAM-57] update package.json from subtheme

---

.gitignore
.travis.yml
composer.json
composer.lock
composer.patches.json
html/modules/custom/pocam_extract/src/Form/Import.php
html/modules/custom/pocam_general/pocam_general.module
symfony.lock

Requesting a review by @lazysoundsystem because I had to reroll the facets patch.

[OPS-7117] Drupal core 8.9.10 and many composer updates.

---

html/themes/custom/common_design_subtheme/gulpfile.js
html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

1. update axios as per dependabot alert
2. replace gulp-sass with dart-sass
3. run `npm audit fix`

CD-213 Dependency updates

---

composer.json
composer.lock
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-global-header.html.twig

As per AR-208 this should fix the Username variable caching issue, with a base theme update.
Also included are some improvements to the OCHA Services menu. To accommodate the moving of the OCHA Services partial to the footer, I've made the same changes in the sub theme.

CD-246 update base theme

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

npm audit fix and socket.io update

CD-213 sub theme dependency updates

---

.travis.yml
README.md
composer.lock

https://humanitarian.atlassian.net/browse/OPS-7442
and updates ubuntu travis version to 'bionic'.

[OPS 7442} core security update

---

composer.lock
config/block.block.common_design_subtheme_help.yml
config/block.block.common_design_subtheme_local_actions.yml
config/block.block.common_design_subtheme_local_tasks.yml
config/block.block.common_design_subtheme_ocha_basic_system_main.yml
config/block.block.common_design_subtheme_page_title.yml

And move page title and tabs into page title region

CD-283 bump base theme version with page title fix

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

Attempt to update `trim` - as per https://github.com/UN-OCHA/common_design/pull/220/files

update package.json for dependabot alerts

---

composer.lock
html/.gitignore
html/modules/.gitignore
html/profiles/.gitignore
html/sites/.gitignore
html/themes/.gitignore

https://humanitarian.atlassian.net/browse/OPS-7493

[OPS-7493] update core to 8.9.16

---

composer.json
composer.lock
config/core.extension.yml
config/google_tag.container.default.yml
config/google_tag.settings.yml
symfony.lock

https://humanitarian.atlassian.net/browse/POCAM-63
Adds tag manager and default configuration.
See also: https://github.com/UN-OCHA/tools-ansible/pull/686/files

[POCAM-63] add tag manager

---

.travis.yml
docker/Dockerfile

Also default to PHP7.4 and composer 2 everywhere.

[POCAM-62][EXTRA]

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

- update xmldom and npm update

CD-298 Dependency updates

---

composer.json
composer.lock

https://humanitarian.atlassian.net/browse/OPS-7688
Note - this deployment will include upgrading to Drupal 9, so deserves some extra clicking around.

[OPS-7688] update core to 9.2.4

---

config/google_tag.container.default.yml
config/google_tag.settings.yml
config/social_auth_hid.settings.yml
config/tour.tour.search-api-index-fields.yml
config/tour.tour.search-api-index-form.yml
config/tour.tour.search-api-index-processors.yml
config/tour.tour.search-api-index.yml
config/tour.tour.search-api-server-form.yml
config/tour.tour.search-api-server.yml
config/tour.tour.views-ui.yml
config/user.mail.yml

With a config export, these changes - mostly whitespace and quotation styles, came along for the ride. Updating them now to get them in sync.

update config - minor changes

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

CD-298  set-value as devDepdendency

---

composer.lock
html/sites/default/default.services.yml

https://humanitarian.atlassian.net/browse/OPS-7780

[OPS-7634] update core to 9.2.6

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

CD-289 nth-check as dev dependency

---

composer.lock
symfony.lock

Run `composer update` generates new lock file and symfony.lock

Dependency updates for symfony/serializer based on Dependabot alert

---

composer.json
composer.lock
html/sites/default/default.services.yml
html/sites/default/default.settings.php
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-8028
https://humanitarian.atlassian.net/browse/OPS-8029

[OPS-8028] update core to 9.3.3

---

composer.json

Add plugins like https://github.com/UN-OCHA/iasc8/pull/562/files - and bump stuck tests from develop to main.

[OPS-8028] add to composer plugin config
